[package]
name = "synchive"
version = "0.1.0"
description = "A media player to watching videos together with friends."
authors = ["akirco"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "synchive_lib"

[dependencies]
pushers = "1.5.0"
reqwest = { version = "0.13.5", features = ["json", "system-proxy"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2.11.6", features = [] }  # features = ["devtools"] }
tauri-plugin-opener = "2.5.5"
tauri-plugin-store = "2.4.5"
tokio = { version = "1.53.1", features = ["full"] }

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
